# Generated by Django 4.2 on 2024-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('TravelID', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=50)),
                ('Money', models.IntegerField()),
                ('Tag', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Journal', models.CharField(max_length=500)),
            ],
        ),
    ]
